services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bsn-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  bsn-api:
    container_name: bsn-api
    image: bsn/bsn-api:latest
    build:
      context: ./book-network
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_HOSTNAME: ${MAIL_HOSTNAME}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5080:5080"
    networks:
      - bsn-network
    depends_on:
      - postgres

  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:latest
    build:
      context: ./book-network-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - bsn-network
    depends_on:
      - bsn-api

networks:
  bsn-network:
    driver: bridge

volumes:
  postgres:
    driver: local
