name: BSN Frontend Pipeline
on:
  push:
    branches:
      - ci/develop
    paths:
        - book-network-ui/*
        - docker-compose.yml
        - .github/workflows/*-backend.yml

jobs:
    build-image:
      runs-on: ubuntu-latest
      name: Build the BSN Frontend Docker image
      steps:
        - name: Checkout the code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Extract the project version
          id: extract_version
          run: |
            cd book-network-ui
            echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}
        - name: Build & Push to DockerHub
          uses: docker/build-push-action@v5
          with:
            context: book-network-ui
            file: docker/frontend/Dockerfile
            push: true
            platforms: linux/amd64
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:latest,${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }}

    # Deploy will fail since we don't have a server to deploy to.
#    deploy:
#      needs: [build-image]
#      runs-on: ubuntu-latest
#      name: Deploy the BSN Frontend
#      steps:
#        - name: Create a deployment folder
#          run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p /app"
#        - name: Copy the docker-compose.yml file to the deployment folder
#          run: scp -oStrictHostKeyChecking=no  docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DEPLOYMENT_FOLDER }}
#        - name: Deploy the BSN Frontend
#          run: |
#            ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
#            cd /app
#            docker-compose -f docker-compose.yml pull -q
#            docker-compose -f docker-compose.yml up -d
#            EOF
